# Generated by Django 4.2.1 on 2023-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['added_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='added_on',
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Draft')], default=1),
        ),
    ]
